[profile.default]
src = "sol"
out = "out"
libs = ["forge-lib"]
fs_permissions = [
	{ access = "read", path = "accounts.superposition.so.wasm"},
	{ access = "read", path = "superposition-precompiles/precompiles-ed25519.wasm"}
]
