[package]
name = "contract"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "contract"

[features]
std = ["bobcat-sdk/std"]
panic-revert = ["superposition_libaccounts/panic-revert"]

[dependencies]
bobcat-sdk.workspace = true
borsh.workspace = true
const-hex.workspace = true
superposition_libaccounts = { version = "0.1.0", path = "../superposition_libaccounts" }
mini-alloc.workspace = true
