[package]
name = "contract"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "contract"

[features]
std = ["bobcat-sdk/std"]
panic-revert = ["libaccounts/panic-revert"]

[dependencies]
bobcat-sdk = { workspace = true, features = ["panic"] }
borsh.workspace = true
libaccounts = { version = "0.1.0", path = "../libaccounts" }
mini-alloc.workspace = true
