
type Query {
  """
  Get the system management ed25519 public key this server is managing. Useful for the
  signing process.
  """
  publickey: String!

  eoaForAddress(address: String!): String!
}

input Permit {
  token: String!,
  deadline: Int!,
  permitV: Int!,
  permitR: String!,
  permitS: String!
}

input FromArgs {
  token: String!,
  to_take: String!,
  max_unspent: String!
}

input SolveArgs {
  permit: [Permit!]!,
  from: [FromArgs!]!,
  target: String!,
  cd: String!,
  ms_ts: String!
}

input CreateAccount {
  eoa_addr: String!,
  sigV: Int!,
  sigR: String!,
  sigS: String!
}

input Mint {
  market: String!,
  outcome: String!,
  amount: String!,
  permit: Permit,
  referrer: String!,

  """
  The millisecond timestamp for making sure this isn't doubled up somehow.
  """
  ms_ts: String!
}

type Mutation {
  """
  Create a new account using the key management service intended for API workers. Returns
  a secret key that can be used to spend from the account.
  """
  createAccountExec(createAccount: CreateAccount!, mint: Mint): String!

  """
  Request the existing secret that was created for this account. It needs a signature of
  the nonce and the public key from the user. The nonce must be greater than what's
  recorded in the database so far.
  """
  requestSecret(
    eoa_addr: String!,
    nonce: Int!,
    sigV: Int!,
    sigR: String!,
    sigS: String!
  ): String!

  """
  Use 9lives to open a position on behalf of the user given, optiomally creating the
  account at the same time. The EOA is fetched from the secret key that the
  user passes to the client.
  """
  ninelivesMint(mint: Mint!): String!
}
