
type Query {
  """
  Get the system management ed25519 public key this server is managing. Useful for the
  signing process.
  """
  publickey: String!

  eoaForAddress(address: String!): String!

  """
  Is this address recorded as having onramped?
  """
  hasCreated(address: String!): Boolean!
}

input Permit {
  deadline: Int!,
  permitV: Int!,
  permitR: String!,
  permitS: String!
}

input FromArgs {
  token: String!,
  to_take: String!,
  max_unspent: String!
}

input SolveArgs {
  permit: [Permit!]!,
  from: [FromArgs!]!,
  target: String!,
  cd: String!,
  ms_ts: String!
}

input CreateAccount {
  eoa_addr: String!,
  sigV: Int!,
  sigR: String!,
  sigS: String!
}

input Mint {
  market: String!,
  outcome: String!,
  amount: String!,
  permit: Permit,
  referrer: String!,

  """
  The millisecond timestamp for making sure this isn't doubled up somehow.
  """
  ms_ts: String!
}

type CreateAccountExec {
  hash: String!,
  secret: String!
}

"""
Statistics for this usage type. Only since 1768801591.
"""
type Statistics {
  """
  The action that took place during this interaction with the accounts system.
  """
  action: String!,

  """
  The average gas limit that was used in the last 24 hours.
  """
  avgGasLimit24Hours: Float!,

  """
  The average gas limit for the last week.
  """
  avgGasLimitWeek: Float!,

  """
  The average gas limit for all time.
  """
  avgGasLimitAllTime: Float!,

  """
  Transactions in the last 24 hours.
  """
  tx24Hours: Int!,

  """
  Transactions from the last 7 days.
  """
  txWeek: Int!,

  """
  Transactions count of all time.
  """
  txAllTime: Int!
}

type Mutation {
  """
  Create a new account using the key management service intended for API workers. Returns
  a secret key that can be used to spend from the account.
  """
  createAccountExec(
      createAccount: CreateAccount!,
      mint: Mint,
      dryrun: Boolean
  ): CreateAccountExec

  """
  Request the existing secret that was created for this account. It needs a signature of
  the nonce and the public key from the user. The nonce must be greater than what's
  recorded in the database so far.
  """
  requestSecret(
    eoa_addr: String!,
    nonce: Int!,
    sigV: Int!,
    sigR: String!,
    sigS: String!,
    dryrun: Boolean
  ): String!

  """
  Use 9lives to open a position on behalf of the user given, optiomally creating the
  account at the same time. The EOA is fetched from the secret key that the
  user passes to the client.
  """
  ninelivesMint(mint: Mint!, dryrun: Boolean): String!

  """
  Claim payoff for the markets given, using the eoa in the header.
  """
  claimRewards(markets: [String!]!, msTs: String!, dryrun: Boolean): String!

  """
  Get information about the different functions being serviced by this graph.
  """
  statistics: [Statistics!]
}
