package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log/slog"

	ethCommon "github.com/ethereum/go-ethereum/common"

	"github.com/fluidity-money/accounts.superposition.so/graph/model"
	"github.com/fluidity-money/accounts.superposition.so/lib/client"
	"github.com/fluidity-money/accounts.superposition.so/lib/db"
	"github.com/fluidity-money/accounts.superposition.so/lib/types"
)

// CreateAccountExec is the resolver for the createAccountExec field.
func (r *mutationResolver) CreateAccountExec(ctx context.Context, createAccount model.CreateAccount, mint *model.Mint) (*model.CreateAccountExec, error) {
	var pubKey [32]byte
	copy(pubKey[:], r.AccPubKey)
	f, err := CreateAccountToFreshBackwards(pubKey, createAccount)
	if err != nil {
		slog.Error("create account",
			"create account", createAccount,
			"mint", mint,
			"err", err,
		)
		return nil, fmt.Errorf("create account: %v", err)
	}
	if !ethCommon.IsHexAddress(createAccount.EoaAddr) {
		return nil, fmt.Errorf("not eoa address")
	}
	eoa := ethCommon.HexToAddress(createAccount.EoaAddr)
	if mint != nil {
		err = TagFreshBackwardsWithMint(
			f,
			r.AccPrivKey,
			r.Fusdc,
			mint.Market,
			mint.Outcome,
			mint.Amount,
			mint.Referrer,
			eoa,
			mint.Permit,
			mint.MsTs,
		)
		if err != nil {
			return nil, fmt.Errorf("mint tagging: %v", err)
		}
	}
	privKey, sender, err := db.PickPrivateKey(r.Db)
	if err != nil {
		slog.Error("error picking private key",
			"err", err,
		)
		return nil, fmt.Errorf("picking private key: %v", err)
	}
	h, err := client.SendArguments(
		ctx,
		r.Client,
		r.ChainId,
		privKey,
		*sender,
		r.AccountsFactoryAddr,
		types.Args{
			Enum:           types.ArgsFreshBackwards,
			FreshBackwards: *f,
		},
		r.Dryrun,
	)
	if err != nil {
		slog.Error("sending arguments",
			"sender", sender,
			"fresh backwards", f,
			"err", err,
		)
		return nil, fmt.Errorf("send arguments: %v", err)
	}
	// We can tolerate a situation where the request drops off here due to a
	// issue with the database, since the frontend willpresumably greedily
	// reauthenticate when the user tries.
	secret := make([]byte, 32)
	if n, err := rand.Read(secret); n != 16 || err != nil {
		slog.Error("error seeding randomness",
			"err", err,
		)
		return nil, fmt.Errorf("error with randomness")
	}
	salt := make([]byte, 16)
	if n, err := rand.Read(salt); n != 16 || err != nil {
		// This isn't very likely, but with Lambda (and money) it's good to
		// exercise caution.
		slog.Error("error seeding randomness",
			"err", err,
		)
		return nil, fmt.Errorf("error with randomness")
	}
	var (
		secretX = hex.EncodeToString(secret)
		saltX   = hex.EncodeToString(salt)
	)
	key := MakeKey(secret, salt)
	keyX := hex.EncodeToString(key)
	if !r.Dryrun {
		_, err = r.Db.Exec(`
INSERT INTO accounts_secrets_1 (eoa_addr, priv_key salt)
VALUES ($1, $2, $3)`,
			eoa.String(),
			keyX,
			saltX,
		)
		if err != nil {
			slog.Error("error executing the insertion of the secret",
				"err", err,
				"eoa addr", eoa,
			)
			return nil, fmt.Errorf("error inserting secret: %v", err)
		}
	}
	return &model.CreateAccountExec{
		Hash:   h.Hex(),
		Secret: secretX,
	}, nil
}

// RequestSecret is the resolver for the requestSecret field.
func (r *mutationResolver) RequestSecret(ctx context.Context, eoaAddr string, nonce int32, sigV int32, sigR string, sigS string) (string, error) {
	panic(fmt.Errorf("not implemented: RequestSecret - requestSecret"))
}

// NinelivesMint is the resolver for the ninelivesMint field.
func (r *mutationResolver) NinelivesMint(ctx context.Context, mint model.Mint) (string, error) {
	if authed, _ := ctx.Value("authed").(bool); !authed {
		return "", fmt.Errorf("not authed")
	}
	eoa, ok := ctx.Value("eoa").(ethCommon.Address)
	if !ok {
		return "", fmt.Errorf("bad eoa address")
	}
	clientAddr := types.GetClientAddr(r.AccountsFactoryAddr, eoa)
	privKey, sender, err := db.PickPrivateKey(r.Db)
	if err != nil {
		slog.Error("error picking private key",
			"err", err,
		)
		return "", fmt.Errorf("picking private key: %v", err)
	}
	f, err := CreateSolveArgsSigArgs(
		r.AccPrivKey,
		r.Fusdc,
		mint.Market,
		mint.Outcome,
		mint.Amount,
		mint.Referrer,
		eoa,
		mint.Permit,
		mint.MsTs,
	)
	h, err := client.SendArguments(
		ctx,
		r.Client,
		r.ChainId,
		privKey,
		*sender,
		clientAddr,
		types.Args{
			Enum: types.ArgsSolve,
			Solve: types.Solve{
				Slot: 0,
				Args: []types.SolveArgsSigArgs{*f},
			},
		},
		r.Dryrun,
	)
	if err != nil {
		slog.Error("sending arguments",
			"sender", sender,
			"solve", f,
			"err", err,
		)
		return "", fmt.Errorf("sending: %v", err)
	}
	return h.Hex(), nil
}

// Publickey is the resolver for the publickey field.
func (r *queryResolver) Publickey(ctx context.Context) (string, error) {
	return hex.EncodeToString(r.AccPubKey), nil
}

// EoaForAddress is the resolver for the eoaForAddress field.
func (r *queryResolver) EoaForAddress(ctx context.Context, address string) (string, error) {
	if ethCommon.IsHexAddress(address) {
		return "", fmt.Errorf("not address")
	}
	e := ethCommon.HexToAddress(address)
	return types.GetClientAddr(r.AccountsFactoryAddr, e).String(), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
