package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
)

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, eoaAddr string, sigV int32, sigR string, sigS string) (string, error) {
	panic(fmt.Errorf("not implemented: CreateAccount - createAccount"))
}

// NinelivesOpenPosition is the resolver for the ninelivesOpenPosition field.
func (r *mutationResolver) NinelivesOpenPosition(ctx context.Context, eoaAddr string, market string, outcome string, amount int32) (string, error) {
	panic(fmt.Errorf("not implemented: NinelivesOpenPosition - ninelivesOpenPosition"))
}

// Publickey is the resolver for the publickey field.
func (r *queryResolver) Publickey(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: Publickey - publickey"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
