[package]
name = "superposition_libaccounts"
version = "0.8.0"
edition = "2024"
license = "MIT"
description = "Superposition accounts calldata and utilities functions. Used to generate calldata for in-browser signing on a single deployment."
homepage = "https://fluiditylabs.io"
repository = "https://github.com/fluidity-money/accounts.superposition.so"

[lib]

[features]
std = ["bobcat-sdk/serde", "bobcat-sdk/ed25519-dalek", "clap"]
panic-revert = ["bobcat-sdk/panic-revert"]
arbitrary = ["dep:arbitrary", "bobcat-sdk/arbitrary", "superposition-assets/arbitrary"]
alloy-enabled = ["bobcat-sdk/alloy-enabled"]
signing = ["bobcat-sdk/ed25519-dalek", "dep:ed25519-dalek"]

[dependencies]
array-concat.workspace = true
borsh.workspace = true
bobcat-sdk = { version = ">=0.9.6", features = ["alloc", "serde", "borsh", "panic-revert"] }
clap = { version = ">=4.0.0", optional = true, features = ["derive"] }
const-hex.workspace = true
serde = { version = ">=1.0.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0.145", default-features = false, features = ["alloc"] }
sha2 = { version = "0.10.9", default-features = false }
proptest = { version = "1.9.0", optional = true }
proptest-derive = { version = "0.7.0", optional = true }
arbitrary = { version = "1.4.2", features = ["derive"], optional = true }
superposition-assets.workspace = true
ed25519-dalek = { version = ">=3.0.0", default-features = false, optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bobcat-sdk = { version = ">=0.9.6", default-features = false, features = ["ed25519-dalek", "ruint-enabled"] }
