// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateAccount struct {
	EoaAddr   string  `json:"eoa_addr"`
	SigV      int32   `json:"sigV"`
	SigR      string  `json:"sigR"`
	SigS      string  `json:"sigS"`
	Authority *string `json:"authority,omitempty"`
}

type CreateAccountExec struct {
	Hash   string `json:"hash"`
	Secret string `json:"secret"`
}

type FromArgs struct {
	Token      string `json:"token"`
	ToTake     string `json:"to_take"`
	MaxUnspent string `json:"max_unspent"`
}

type Mint struct {
	Market   string  `json:"market"`
	Outcome  string  `json:"outcome"`
	Amount   string  `json:"amount"`
	Permit   *Permit `json:"permit,omitempty"`
	Referrer string  `json:"referrer"`
	// The millisecond timestamp for making sure this isn't doubled up somehow.
	MsTs string `json:"ms_ts"`
}

type Mutation struct {
}

type Permit struct {
	Deadline int32  `json:"deadline"`
	PermitV  int32  `json:"permitV"`
	PermitR  string `json:"permitR"`
	PermitS  string `json:"permitS"`
}

type Query struct {
}

type SolveArgs struct {
	Permit []*Permit   `json:"permit"`
	From   []*FromArgs `json:"from"`
	Target string      `json:"target"`
	Cd     string      `json:"cd"`
	MsTs   string      `json:"ms_ts"`
}

// Statistics for this usage type. Only since 1768801591.
type Statistics struct {
	// The action that took place during this interaction with the accounts system.
	Action string `json:"action"`
	// The average gas limit that was used in the last 24 hours.
	AvgGasLimit24Hours float64 `json:"avgGasLimit24Hours"`
	// The average gas limit for the last week.
	AvgGasLimitWeek float64 `json:"avgGasLimitWeek"`
	// The average gas limit for all time.
	AvgGasLimitAllTime float64 `json:"avgGasLimitAllTime"`
	// Transactions in the last 24 hours.
	Tx24Hours int32 `json:"tx24Hours"`
	// Transactions from the last 7 days.
	TxWeek int32 `json:"txWeek"`
	// Transactions count of all time.
	TxAllTime int32 `json:"txAllTime"`
}

type Asset string

const (
	AssetUsdc Asset = "USDC"
	AssetArb  Asset = "ARB"
	AssetWeth Asset = "WETH"
)

var AllAsset = []Asset{
	AssetUsdc,
	AssetArb,
	AssetWeth,
}

func (e Asset) IsValid() bool {
	switch e {
	case AssetUsdc, AssetArb, AssetWeth:
		return true
	}
	return false
}

func (e Asset) String() string {
	return string(e)
}

func (e *Asset) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Asset(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Asset", str)
	}
	return nil
}

func (e Asset) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Asset) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Asset) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
