[package]
name = "accounts-cli"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
array-concat.workspace = true
bobcat-sdk.workspace = true
borsh.workspace = true
clap = { version = "4.5.53", features = ["derive"] }
const-hex.workspace = true
ed25519-dalek = { version = "2.1.1", default-features = false, features = ["digest"] }
superposition_libaccounts = { version = "0.3.0", path = "../superposition_libaccounts" }
mini-alloc.workspace = true
superposition-assets.workspace = true
