[package]
name = "libaccounts"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]

[features]
std = ["bobcat-sdk/serde", "clap"]
panic-revert = ["bobcat-sdk/panic-revert"]

[dependencies]
array-concat.workspace = true
borsh.workspace = true
ed25519-dalek.workspace = true
lzss.workspace = true
bobcat-sdk.workspace = true
clap = { version = ">=4.0.0", optional = true, features = ["derive"] }
const-hex.workspace = true
serde = { version = ">=1.0.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0.145", default-features = false, features = ["alloc"] }

[dev-dependencies]
proptest = "1.9.0"
